import type { PhaseCommandPolicy } from './types.ts';

export const PHASE_COMMAND_POLICY = {
  menu: {
    selectDifficulty: 'accept',
    start: 'accept',
    direction: 'ignore',
    pause: 'ignore',
    resume: 'ignore',
    restart: 'ignore',
    returnToMenu: 'ignore',
    toggleMute: 'accept',
  },
  ready: {
    selectDifficulty: 'ignore',
    start: 'ignore',
    direction: 'validateDirection',
    pause: 'ignore',
    resume: 'ignore',
    restart: 'ignore',
    returnToMenu: 'ignore',
    toggleMute: 'accept',
  },
  playing: {
    selectDifficulty: 'ignore',
    start: 'ignore',
    direction: 'validateDirection',
    pause: 'accept',
    resume: 'ignore',
    restart: 'ignore',
    returnToMenu: 'ignore',
    toggleMute: 'accept',
  },
  paused: {
    selectDifficulty: 'ignore',
    start: 'ignore',
    direction: 'ignore',
    pause: 'ignore',
    resume: 'accept',
    restart: 'ignore',
    returnToMenu: 'ignore',
    toggleMute: 'accept',
  },
  gameOver: {
    selectDifficulty: 'ignore',
    start: 'ignore',
    direction: 'ignore',
    pause: 'ignore',
    resume: 'ignore',
    restart: 'accept',
    returnToMenu: 'accept',
    toggleMute: 'accept',
  },
  won: {
    selectDifficulty: 'ignore',
    start: 'ignore',
    direction: 'ignore',
    pause: 'ignore',
    resume: 'ignore',
    restart: 'accept',
    returnToMenu: 'accept',
    toggleMute: 'accept',
  },
} as const satisfies PhaseCommandPolicy;
